### ISSUE TITLE
Make install process automated on ubuntu

### ISSUE THREAD

**Issue by tdurand** [meso-unimpressed/darknet-net#5]
We are in the process of shipping a "ready-to-use" software for the project using this darknet-net fork and we need to do a easy installer for ubuntu of the ./darknet-net command

cc @b-g

**Comment by RoaldWikene** [comment]
Hi. 
i have a suggestion

Would it be possible to update the make file for darknet-net ?

Sample flags for generation on CUDA 9 for maximum compatibility. Note the removed SM_20:

-arch=sm_30 \
 -gencode=arch=compute_30,code=sm_30 \
 -gencode=arch=compute_50,code=sm_50 \
 -gencode=arch=compute_52,code=sm_52 \
 -gencode=arch=compute_60,code=sm_60 \
 -gencode=arch=compute_61,code=sm_61 \
 -gencode=arch=compute_62,code=sm_62 \
 -gencode=arch=compute_70,code=sm_70 \
 -gencode=arch=compute_70,code=compute_70

**Comment by PTS93** [comment]
Sure feel free to submit a pull request!

At some point I will update the code base to the latest darknet version as there have been quite a few improvements.

**Comment by RoaldWikene** [comment]
@PTS93 created https://github.com/meso-unimpressed/darknet-net/pull/7  :)
